framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
        routing:
            App\Notification\RequestPasswordNotification: async
            App\Notification\ResetPasswordNotification: async
